project:
  type: website

website:
  title: "E155 Prpject: Remy the Rat"
  navbar:
    left:
      - href: documentation.qmd
        text: Documentation
      - href: fpga.qmd
        text: FPGA
      - href: mcu.qmd
        text: MCU
      - href: results.qmd
        text: Results
      - href: team.qmd
        text: Team
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



